# Introduction {#sec1}
Covid-19 pandemic primarily recognized as a health crisis, has significantly impacted different economic aspects of international order, especially that of international trade. Many economies introduced measures to combat the pandemic and deal with an escalation in Covid-19 cases. More than 50 economies changed port protocols, ranging from port closure to additional documentation, resulting in reduced global trade volume. Similarly, imposition of health and safety measures for trade partners has disrupted the performance of the global supply chain [@oecd2020covid]. According to world trade statistical review 2021, due to pandemic pressure, the volume of world merchandise trade reduced by 5.3 percent during 2020. This contraction in the trade volume started in the first quarter, recorded a two percent fall in the trade volume, and accentuated the fall in the second quarter with a massive decline of 12.5 percent. However, the subsequent rebound in the third and fourth quarters show recovery and predicts the return of merchandise trade to its pre-pandemic peaks.


India is not an exception to this scenario. During the pre-pandemic period, India emerged as a key player in Global Production Networks (GPN) with higher trade in intermediate products [@Vidya2020a]. However, Covid-19 interrupted GPN by reducing the supply of intermediate products due to suspension of production as a result of imposed national lockdown [@Vidya2020]. Further, the pandemic set a natural wave of 'deglobalization,' forcing countries to shut down their borders resulted a decline in the Indian trade [@rajesh2020economy; @Veeramani2021]. Given these situations, India recorded an 8.6 percent decline in merchandise exports in the first quarter of 2020 which further declined sharply to the tune of 30.1 percent in the second quarter. On a similar note, the imports also fell precipitously in the second quarter, recording a decline of 47.4 percent compared to the 2.3 percent fall in the first quarter of 2020. However, during different unlock phases of lockdown (third and fourth quarters), India recorded significant improvement in the total trade volume.


Emerging literature has begun to examine the effects of the Covid-19 pandemic on international trade. @Hayakawa2021 analyze the pandemic as a burden for exporting countries, specifically developing countries. @Vidya2020 identified that pandemic induced supply chain disruptions and reduced trade interconnectedness and connectivity among countries. @Chong2021 compared the balance of payment performance of ASEAN countries. All these empirical works are mainly based on the information from the early phase of Covid-19. Further, the studies pertaining to the Covid-19 and trade in the context of India are relatively scant in literature. 


Given this backdrop, we analyse the impact of the Covid-19 pandemic on Indian trade using the method of intervention time series analysis. Since the existing studies have emphasized on the initial phase of Covid-19, our study will incorporate  immediate impact of Covid-19 on trade and its influence in the recovering stages. The study will help to throw new light on the evolution of crucial trade statistics of India in the post-lockdown periods. The results of the study will assist in determining the immediate as well as long term impact of Covid-19 on international trade variables.